import express from 'express';

const getMovies = (_req: express.Request, res: express.Response): void => {
  res.json([
    {
      overview:
        'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
      release_date: '2008-07-14',
      original_title: 'The Dark Knight',
      poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
      adult: false,
      backdrop_path: '/6fA9nie4ROlkyZAUlgKNjGNCbHG.jpg',
      vote_average: 8.5,
      genre_ids: [18, 28, 80, 53],
      vote_count: 25844,
      original_language: 'en',
      video: false,
      title: 'The Dark Knight',
      id: 155,
      popularity: 65.503,
    },
    {
      backdrop_path: '/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg',
      genre_ids: [18, 36, 10752],
      original_language: 'en',
      original_title: "Schindler's List",
      poster_path: '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
      video: false,
      vote_average: 8.6,
      vote_count: 11816,
      overview:
        'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
      release_date: '1993-11-30',
      title: "Schindler's List",
      id: 424,
      adult: false,
      popularity: 29.37,
    },
    {
      adult: false,
      backdrop_path: '/rr7E0NoGKxvbkb89eR1GwfoYjpA.jpg',
      genre_ids: [18],
      vote_count: 22425,
      original_language: 'en',
      original_title: 'Fight Club',
      poster_path: '/a26cQPRhJPX6GbWfQbvZdrrp9j9.jpg',
      title: 'Fight Club',
      video: false,
      vote_average: 8.4,
      release_date: '1999-10-15',
      overview:
        'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
      id: 550,
      popularity: 37.659,
    },
    {
      adult: false,
      backdrop_path: '/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg',
      genre_ids: [35, 18, 10749],
      id: 13,
      original_language: 'en',
      original_title: 'Forrest Gump',
      overview:
        'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
      poster_path: '/saHP97rTPS5eLmrLQEcANmKrsFl.jpg',
      release_date: '1994-07-06',
      title: 'Forrest Gump',
      video: false,
      vote_average: 8.5,
      vote_count: 21246,
      popularity: 40.915,
    },
    {
      poster_path: '/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
      video: false,
      id: 27205,
      overview:
        'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious.',
      release_date: '2010-07-15',
      vote_count: 29861,
      adult: false,
      backdrop_path: '/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
      vote_average: 8.3,
      genre_ids: [28, 878, 12],
      title: 'Inception',
      original_language: 'en',
      original_title: 'Inception',
      popularity: 51.549,
    },
    {
      adult: false,
      backdrop_path: '/icmmSD4vTTDKOq2vvdulafOGw93.jpg',
      genre_ids: [28, 878],
      id: 603,
      original_language: 'en',
      original_title: 'The Matrix',
      poster_path: '/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
      title: 'The Matrix',
      vote_average: 8.2,
      overview:
        'Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.',
      release_date: '1999-03-30',
      vote_count: 19864,
      video: false,
      popularity: 110.91,
    },
  ]);
};

export { getMovies };
